clear all; clc; close all;
% this file takes data and processes it. that's it.
% code generated by cringe AI bot bc I cba to format my graphs beautifully by hand
% Load the data file
load('./RCload_data.mat');
v_out_sig        = data.getElement(2);
t                = v_out_sig.Values.Time;
i_out            = data.getElement(1).Values.Data;
v_out            = v_out_sig.Values.Data;
inductor_current = data.getElement(3).Values.Data;

% Formatting variables
lw       = 1.5;
fontName = 'CMU Serif';
fontSize = 12;

t_end = t(end);
t_ss  = t_end - 0.2;   % steady state window start

%% 1. V_out Plot (full duration + steady state zoom)
figure('Color', 'w');
subplot(2,1,1);
plot(t, v_out, 'LineWidth', lw);
hold on;
yline(400, '--r', '400V Target', 'LineWidth', 1.2, 'FontName', fontName);
xlim([0 t_end]);
ylim([0 440]);
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

subplot(2,1,2);
mask_v = (t >= t_ss & t <= t_end);
plot(t(mask_v), v_out(mask_v), 'LineWidth', lw);
xlim([t_ss t_end]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;
exportgraphics(gcf, 'V_out_RC.pdf', 'ContentType', 'vector');

%% 2. I_out Plot (full duration + steady state zoom)
figure('Color', 'w');
subplot(2,1,1);
plot(t, i_out, 'LineWidth', lw);
xlim([0 t_end]);
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

subplot(2,1,2);
plot(t(mask_v), i_out(mask_v), 'LineWidth', lw);
xlim([t_ss t_end]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;
exportgraphics(gcf, 'I_out_RC.pdf', 'ContentType', 'vector');

%% 3. Inductor Current (full duration + steady state zoom)
figure('Color', 'w');
subplot(2,1,1);
plot(t, inductor_current, 'LineWidth', lw);
xlim([0 t_end]);
ylabel('Inductor Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

subplot(2,1,2);
plot(t(mask_v), inductor_current(mask_v), 'LineWidth', lw);
xlim([t_ss t_end]);
ylabel('Inductor Current (A)', 'FontName', fontName);
xlabel('Time (s)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;
exportgraphics(gcf, 'inductor_current_RC.pdf', 'ContentType', 'vector');