clear all; clc; close all; 
% this file takes data and processes it. that's it.

% code generated by cringe AI bot bc I cba to format my graphs beautifully by hand

% Load the data file
load('./RC_load_graphs.mat');

v_out_sig = data.getElement('V_out');
t         = v_out_sig.Values.Time;
v_out     = v_out_sig.Values.Data;
i_out     = data.getElement('I_out').Values.Data;
ind_curr  = data.getElement('inductor_current').Values.Data;

% Formatting variables
lw       = 1.5;
fontName = 'CMU Serif';
fontSize = 12;

%% 1. V_out Plot (0 to 10s)
figure('Color', 'w');
subplot(2,1,1);
plot(t, v_out, 'LineWidth', lw);
hold on;
yline(400, '--r', '400V Target', 'LineWidth', 1.2, 'FontName', fontName);
xlim([0 10]);
ylim([0 440]);
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

%% 2. V_out Ripple (9.7-10s)
subplot(2,1,2);
mask_v = (t >= 9.8 & t <= 10);
t_v    = t(mask_v);
v_v    = v_out(mask_v);

plot(t_v, v_v, 'LineWidth', lw);
xlim([9.8 10]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'V_out_RC.pdf', 'ContentType', 'vector');

%% 3. I_out Plot (0 to 10s)
figure('Color', 'w');
subplot(2,1,1);
plot(t, i_out, 'LineWidth', lw);
hold on;
xlim([0 10]);
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

%% 4. I_out Zoom (9.7 to 10s)
subplot(2,1,2);
mask_i = (t >= 9.7 & t <= 10);
t_i    = t(mask_i);
i_i    = i_out(mask_i);

plot(t_i, i_i, 'LineWidth', lw);
xlim([9.7 10]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'I_out_RC.pdf', 'ContentType', 'vector');

%% 5. Inductor Current 
figure('Color', 'w');
mask_pfc = (t >= 9.7 & t <= 10);

plot(t(mask_pfc), ind_curr(mask_pfc), 'LineWidth', lw);
hold on;

xlim([9.8 10]);
ylabel('Inductor Current (A)', 'FontName', fontName);
xlabel('Time (s)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'inductor_current_RC.pdf', 'ContentType', 'vector');