clear all; clc; close all; 
% this file takes data and processes it. that's it.

% code generated by cringe AI bot bc I cba to format my graphs beautifully by hand

% Load the data file
load('./controller_w_r_load_data.mat');

v_out_sig = data.getElement('V_out');
t         = v_out_sig.Values.Time;
v_out     = v_out_sig.Values.Data;
i_out     = data.getElement('I_out').Values.Data;
curr_draw = data.getElement('current_draw').Values.Data;
ind_curr  = data.getElement('inductor_current').Values.Data;

% Formatting variables
lw       = 1.5;
fontName = 'CMU Serif';
fontSize = 12;

%% 1. V_out Plot (0 to 2s)
figure('Color', 'w');
subplot(2,1,1);
plot(t, v_out, 'LineWidth', lw);
hold on;
yline(400, '--r', '400V Target', 'LineWidth', 1.2, 'FontName', fontName);
xlim([0 2]);
ylim([0 440]);
xline(0.1, '--', '$C_v (s)$ on', ...
    'LineWidth', 1.2, ...
    'FontName', fontName, ...
    'FontSize', fontSize, ...
    'LabelVerticalAlignment', 'top', ...
    'LabelHorizontalAlignment', 'right', ...
    'Interpreter', 'latex');
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

%% 2. V_out Ripple (0.58 to 0.65s)
subplot(2,1,2);
mask_v = (t >= 0.58 & t <= 0.65);
t_v    = t(mask_v);
v_v    = v_out(mask_v);

% Hardcoded ripple points
t_vmin = 0.6023; v_min = 384.07;
t_vmax = 0.5981; v_max = 387.21;
v_ripple = v_max - v_min;

plot(t_v, v_v, 'LineWidth', lw);
hold on;
plot(t_vmin, v_min, 'o', 'MarkerFaceColor', 'b');
plot(t_vmax, v_max, 'o', 'MarkerFaceColor', 'b');
text(t_vmax, v_max + 1, sprintf('Ripple: %.2f V', v_ripple), ...
    'FontName', fontName, 'FontWeight', 'bold');
xlim([0.58 0.65]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Voltage (V)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'V_out.pdf', 'ContentType', 'vector');

%% 3. I_out Plot (0 to 1s)
figure('Color', 'w');
subplot(2,1,1);
plot(t, i_out, 'LineWidth', lw);
hold on;
yline(36, '--r', '36A Target', 'LineWidth', 1.2, 'FontName', fontName);
xlim([0 2]);
xline(0.1, '--', '$C_v (s)$ on', ...
    'LineWidth', 1.2, ...
    'FontName', fontName, ...
    'FontSize', fontSize, ...
    'LabelVerticalAlignment', 'top', ...
    'LabelHorizontalAlignment', 'right', ...
    'Interpreter', 'latex');
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

%% 4. I_out Ripple (0.58 to 0.65s)
subplot(2,1,2);
i_v = i_out(mask_v);

% Hardcoded ripple points
t_imin = 0.6023; i_min = 34.600;
t_imax = 0.5981; i_max = 34.880;
i_ripple = i_max - i_min;

plot(t_v, i_v, 'LineWidth', lw);
hold on;
plot(t_imin, i_min, 'o', 'MarkerFaceColor', 'b');
plot(t_imax, i_max, 'o', 'MarkerFaceColor', 'b');
text(t_imax, i_max + 0.05, sprintf('Ripple: %.2f A', i_ripple), ...
    'FontName', fontName, 'FontWeight', 'bold');
xlim([0.58 0.65]);
xlabel('Time (s)', 'FontName', fontName);
ylabel('Current (A)', 'FontName', fontName);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'I_out.pdf', 'ContentType', 'vector');

%% 5. Current Draw & Inductor Current
figure('Color', 'w');
mask_zoom = (t >= 1.5 & t <= 1.6);

% Current Draw
subplot(2,1,1);
plot(t(mask_zoom), curr_draw(mask_zoom), 'LineWidth', lw);
ylabel('Current Draw (A)', 'FontName', fontName);
xlim([1.5 1.6]);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

% Inductor Current
subplot(2,1,2);
plot(t(mask_zoom), ind_curr(mask_zoom), 'LineWidth', lw);
ylabel('Inductor Current (A)', 'FontName', fontName);
xlabel('Time (s)', 'FontName', fontName);
xlim([1.5 1.6]);
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

exportgraphics(gcf, 'curr_draw_and_inductor.pdf', 'ContentType', 'vector');

%% 6. Inductor Current with Annotations (0 to 0.5s)
figure('Color', 'w');
mask_pfc = (t >= 0 & t <= 0.5);

plot(t(mask_pfc), ind_curr(mask_pfc), 'LineWidth', lw);
hold on;

xline(0.1, '--k', '$C_v (s)$ on', ...
    'LineWidth', 1.2, ...
    'FontName', fontName, ...
    'FontSize', fontSize, ...
    'LabelVerticalAlignment', 'top', ...
    'LabelHorizontalAlignment', 'right', ...
    'Interpreter', 'latex');

xlim([0 0.5]);
ylabel('Inductor Current (A)', 'FontName', fontName);
xlabel('Time (s)', 'FontName', fontName);

% Clean formatting for the report
set(gca, 'TickLabelInterpreter', 'latex', 'FontName', fontName, 'FontSize', fontSize);
grid on;

% Exporting to PDF for vector quality
exportgraphics(gcf, 'inductor_current_annotated.pdf', 'ContentType', 'vector');